version: "3"
services:
  jupyter:
    build: .
    volumes:
      - $PWD:/tmp/working
    working_dir: "/tmp/working"
    container_name: analysis-sample
    ports:
      - "8080:8080"
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.notebook_dir=''